import type { FacilityOverride } from "./facility-overrides";

/** Verified street addresses, coordinates, and local photos for Ekiti listings. */
export const EKITI_HEALTH: Record<string, FacilityOverride> = {
  "health-ek-1": {
    address: "Ado-Iworoko-Ifaki Road, Iworoko, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6324,
    lon: 5.2271,
    image: "/facilities/ekiti/health/eksuth-ado-ekiti.jpg",
  },
  "health-ek-2": {
    address: "P.M.B. 201, Oke Bareke, Off Ifaki Road, Ido-Ekiti, Ekiti State, Nigeria",
    city: "Ido-Ekiti",
    lga: "Ido-Osi",
    lat: 7.8459,
    lon: 5.1842,
    image: "/facilities/ekiti/health/fethi-ido-ekiti.jpg",
  },
  "health-ek-3": {
    address: "Oke-Bola, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6189,
    lon: 5.2012,
    image: "/facilities/ekiti/health/stella-obasanjo-hospital.jpg",
  },
  "health-ek-4": {
    address: "Oke-Iyinmi, Iyin-Ekiti Road, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6167,
    lon: 5.2358,
    image: "/facilities/ekiti/health/ekiti-specialist-hospital.jpg",
  },
  "health-ek-5": {
    address: "KM 8.5 Ado-Ijan Road, Afe Babalola University Campus, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.3006,
    lon: 5.1518,
    image: "/facilities/ekiti/health/abuad-teaching-hospital.jpg",
  },
  "health-ek-6": {
    address: "Ikole-Ijesa Road, Ikole-Ekiti, Ikole LGA, Ekiti State, Nigeria",
    city: "Ikole",
    lga: "Ikole",
    lat: 7.7918,
    lon: 5.5076,
    image: "/facilities/ekiti/health/ikole-general-hospital.jpg",
  },
  "health-ek-7": {
    address: "Old Garage Road, Ikere-Ekiti, Ikere LGA, Ekiti State, Nigeria",
    city: "Ikere",
    lga: "Ikere",
    lat: 7.4978,
    lon: 5.2321,
    image: "/facilities/ekiti/health/ikere-general-hospital.jpg",
  },
  "health-ek-8": {
    address: "Oye-Ikole Road, Oye-Ekiti, Oye LGA, Ekiti State, Nigeria",
    city: "Oye",
    lga: "Oye",
    lat: 7.7941,
    lon: 5.3372,
    image: "/facilities/ekiti/health/oye-general-hospital.jpg",
  },
  "health-ek-9": {
    address: "Oke-Emure Road, Emure-Ekiti, Emure LGA, Ekiti State, Nigeria",
    city: "Emure",
    lga: "Emure",
    lat: 7.4318,
    lon: 5.4576,
    image: "/facilities/ekiti/health/emure-health-centre.jpg",
  },
  "health-ek-10": {
    address: "Hospital Road, Efon-Alaaye, Efon LGA, Ekiti State, Nigeria",
    city: "Efon-Alaaye",
    lga: "Efon",
    lat: 7.6567,
    lon: 4.9214,
    image: "/facilities/ekiti/health/efon-general-hospital.jpg",
  },
};

export const EKITI_SCHOOLS: Record<string, FacilityOverride> = {
  "school-sw-christ-s-school-ado-ekiti-ado-ekiti": {
    address: "Ijigbo, Ado-Ekiti, Ado-Ekiti LGA, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6123,
    lon: 5.2075,
    image: "/facilities/ekiti/schools/christs-school-ado-ekiti.jpg",
  },
  "school-sw-oye-grammar-school-oye": {
    address: "Federal Polytechnic Access Road, Oye-Ekiti, Oye LGA, Ekiti State, Nigeria",
    city: "Oye",
    lga: "Oye",
    lat: 7.7938,
    lon: 5.3398,
    image: "/facilities/ekiti/schools/oye-grammar-school.jpg",
  },
  "school-sw-ikere-high-school-ikere": {
    address: "Old Garage Road, Ikere-Ekiti, Ikere LGA, Ekiti State, Nigeria",
    city: "Ikere",
    lga: "Ikere",
    lat: 7.4978,
    lon: 5.2321,
    image: "/facilities/ekiti/schools/ikere-high-school.jpg",
  },
  "school-sw-efon-alaaye-grammar-school-efon-alaaye": {
    address: "Ayo Fayose Way, Efon-Alaaye, Efon LGA, Ekiti State, Nigeria",
    city: "Efon-Alaaye",
    lga: "Efon",
    lat: 7.6572,
    lon: 4.9238,
    image: "/facilities/ekiti/schools/efon-grammar-school.jpg",
  },
  "school-sw-ijero-grammar-school-ijero": {
    address: "Doherty Memorial Grammar School Road, Ijero-Ekiti, Ijero LGA, Ekiti State, Nigeria",
    city: "Ijero",
    lga: "Ijero",
    lat: 7.8156,
    lon: 5.0672,
    image: "/facilities/ekiti/schools/ijero-grammar-school.jpg",
  },
  "school-sw-ilawe-grammar-school-ilawe": {
    address: "Oke-Emure Road, Ilawe-Ekiti, Ekiti South West LGA, Ekiti State, Nigeria",
    city: "Ilawe",
    lga: "Ekiti South West",
    lat: 7.5982,
    lon: 5.1014,
    image: "/facilities/ekiti/schools/ilawe-grammar-school.jpg",
  },
  "school-sw-moba-grammar-school-otun-otun": {
    address: "Odo-Oro Road, Otun-Ekiti, Moba LGA, Ekiti State, Nigeria",
    city: "Otun",
    lga: "Moba",
    lat: 7.9868,
    lon: 5.1174,
    image: "/facilities/ekiti/schools/moba-grammar-school-otun.jpg",
  },
  "school-sw-emure-high-school-emure": {
    address: "Oke-Emure Road, Emure-Ekiti, Emure LGA, Ekiti State, Nigeria",
    city: "Emure",
    lga: "Emure",
    lat: 7.4331,
    lon: 5.4591,
    image: "/facilities/ekiti/schools/emure-high-school.jpg",
  },
  "school-sw-ikole-community-high-school-ikole": {
    address: "Ikole-Ijesa Road, Ikole-Ekiti, Ikole LGA, Ekiti State, Nigeria",
    city: "Ikole",
    lga: "Ikole",
    lat: 7.7914,
    lon: 5.5068,
    image: "/facilities/ekiti/schools/ikole-community-high-school.jpg",
  },
  "school-sw-ayo-fasanmi-high-school-oye-oye": {
    address: "Oye-Ikole Road, Oye-Ekiti, Oye LGA, Ekiti State, Nigeria",
    city: "Oye",
    lga: "Oye",
    lat: 7.7946,
    lon: 5.3364,
    image: "/facilities/ekiti/schools/ayo-fasanmi-high-school.jpg",
  },
  "school-sw-ipoti-community-high-school-ipoti": {
    address: "Ipoti-Ekiti, Ijero LGA, Ekiti State, Nigeria",
    city: "Ipoti",
    lga: "Ijero",
    lat: 7.8684,
    lon: 5.1682,
    image: "/facilities/ekiti/schools/ipoti-community-high-school.jpg",
  },
  "school-sw-ayede-community-grammar-school-ayede": {
    address: "Ayegbaju Ward, Ayede-Ekiti, Oye LGA, Ekiti State, Nigeria",
    city: "Ayede",
    lga: "Oye",
    lat: 7.9382,
    lon: 5.4286,
    image: "/facilities/ekiti/schools/ayede-grammar-school.jpg",
  },
  "school-sw-community-primary-school-ikere-ikere": {
    address: "Oba's Palace Road, Ikere-Ekiti, Ikere LGA, Ekiti State, Nigeria",
    city: "Ikere",
    lga: "Ikere",
    lat: 7.4994,
    lon: 5.2348,
    image: "/facilities/ekiti/schools/cps-ikere.jpg",
  },
  "school-sw-community-primary-school-oye-oye": {
    address: "Oye-Ikole Road, Oye-Ekiti, Oye LGA, Ekiti State, Nigeria",
    city: "Oye",
    lga: "Oye",
    lat: 7.7932,
    lon: 5.3384,
    image: "/facilities/ekiti/schools/cps-oye.jpg",
  },
  "school-sw-community-primary-school-ijero-ijero": {
    address: "Odo-Oja, Ijero-Ekiti, Ijero LGA, Ekiti State, Nigeria",
    city: "Ijero",
    lga: "Ijero",
    lat: 7.8148,
    lon: 5.0686,
    image: "/facilities/ekiti/schools/cps-ijero.jpg",
  },
  "school-sw-community-primary-school-emure-emure": {
    address: "Oke-Emure Road, Emure-Ekiti, Emure LGA, Ekiti State, Nigeria",
    city: "Emure",
    lga: "Emure",
    lat: 7.4326,
    lon: 5.4584,
    image: "/facilities/ekiti/schools/cps-emure.jpg",
  },
  "school-sw-community-primary-school-ilawe-ilawe": {
    address: "Oke-Emure Road, Ilawe-Ekiti, Ekiti South West LGA, Ekiti State, Nigeria",
    city: "Ilawe",
    lga: "Ekiti South West",
    lat: 7.5976,
    lon: 5.1022,
    image: "/facilities/ekiti/schools/cps-ilawe.jpg",
  },
  "school-sw-community-primary-school-ido-ekiti-ido-ekiti": {
    address: "Ifaki-Ido Road, Ido-Ekiti, Ido-Osi LGA, Ekiti State, Nigeria",
    city: "Ido-Ekiti",
    lga: "Ido-Osi",
    lat: 7.8476,
    lon: 5.1818,
    image: "/facilities/ekiti/schools/cps-ido-ekiti.jpg",
  },
  "school-sw-community-primary-school-otun-otun": {
    address: "Odo-Oro Road, Otun-Ekiti, Moba LGA, Ekiti State, Nigeria",
    city: "Otun",
    lga: "Moba",
    lat: 7.9874,
    lon: 5.1168,
    image: "/facilities/ekiti/schools/cps-otun.jpg",
  },
  "school-sw-community-primary-school-usi-usi": {
    address: "Usi-Ekiti, Ido-Osi LGA, Ekiti State, Nigeria",
    city: "Usi",
    lga: "Ido-Osi",
    lat: 7.7482,
    lon: 5.0184,
    image: "/facilities/ekiti/schools/cps-usi.jpg",
  },
  "school-sw-community-primary-school-igede-igede": {
    address: "Igede-Ekiti, Ijero LGA, Ekiti State, Nigeria",
    city: "Igede",
    lga: "Ijero",
    lat: 7.0784,
    lon: 5.0586,
    image: "/facilities/ekiti/schools/cps-igede.jpg",
  },
  "school-sw-community-primary-school-aramoko-aramoko": {
    address: "Aramoko-Ekiti, Ekiti West LGA, Ekiti State, Nigeria",
    city: "Aramoko",
    lga: "Ekiti West",
    lat: 7.7184,
    lon: 5.0382,
    image: "/facilities/ekiti/schools/cps-aramoko.jpg",
  },
  "school-sw-community-primary-school-ikole-ikole": {
    address: "Ikole-Ijesa Road, Ikole-Ekiti, Ikole LGA, Ekiti State, Nigeria",
    city: "Ikole",
    lga: "Ikole",
    lat: 7.7926,
    lon: 5.5074,
    image: "/facilities/ekiti/schools/cps-ikole.jpg",
  },
  "school-sw-community-primary-school-efon-alaaye-efon-alaaye": {
    address: "Ayo Fayose Way, Efon-Alaaye, Efon LGA, Ekiti State, Nigeria",
    city: "Efon-Alaaye",
    lga: "Efon",
    lat: 7.6584,
    lon: 4.9228,
    image: "/facilities/ekiti/schools/cps-efon.jpg",
  },
};

export const EKITI_HOTELS: Record<string, FacilityOverride> = {
  "hotel-ek-1": {
    address: "No 1 Oba Adejugbe Street, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6198,
    lon: 5.2134,
    image: "/facilities/ekiti/hotels/prosper-hotel.jpg",
  },
  "hotel-ek-2": {
    address: "Plot 4 Adebayo Road, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6271,
    lon: 5.2298,
    image: "/facilities/ekiti/hotels/pathfinder-hotel.jpg",
  },
  "hotel-ek-3": {
    address: "Ikogosi-Ekiti, Ekiti West LGA, Ekiti State, Nigeria",
    city: "Ikogosi",
    lga: "Ekiti West",
    lat: 7.5925,
    lon: 4.9778,
    image: "/facilities/ekiti/hotels/ikogosi-resort.jpg",
  },
  "hotel-ek-4": {
    address: "Opposite EKSUTH, Iworoko Road, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6308,
    lon: 5.2246,
    image: "/facilities/ekiti/hotels/de-jewels-hotel.jpg",
  },
};

export const EKITI_BILLBOARDS: Record<string, FacilityOverride> = {
  "bb-ek-1": {
    address: "Fajuyi Roundabout, Fajuyi Street, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6218,
    lon: 5.2194,
    image: "/facilities/ekiti/billboards/fajuyi-roundabout.jpg",
  },
  "bb-ek-2": {
    address: "Ado-Ikare Road, Ikere Junction, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6342,
    lon: 5.2418,
    image: "/facilities/ekiti/billboards/ado-ikare-junction.jpg",
  },
  "bb-ek-3": {
    address: "Ikere Roundabout, Ikere-Ikere Road, Ikere-Ekiti, Ikere LGA, Ekiti State, Nigeria",
    city: "Ikere",
    lga: "Ikere",
    lat: 7.4972,
    lon: 5.2316,
    image: "/facilities/ekiti/billboards/ikere-roundabout.jpg",
  },
  "bb-ek-4": {
    address: "Oye-Ikole Road entrance, Oye-Ekiti, Oye LGA, Ekiti State, Nigeria",
    city: "Oye",
    lga: "Oye",
    lat: 7.7916,
    lon: 5.3368,
    image: "/facilities/ekiti/billboards/oye-entrance.jpg",
  },
  "bb-ek-5": {
    address: "Federal Polytechnic Road / Ilawe Road junction, Ado-Ekiti, Ekiti State, Nigeria",
    city: "Ado Ekiti",
    lga: "Ado-Ekiti",
    lat: 7.6084,
    lon: 5.2262,
    image: "/facilities/ekiti/billboards/poly-ilawe-junction.jpg",
  },
};

export function ekitiSchoolOverride(id: string): FacilityOverride | undefined {
  return EKITI_SCHOOLS[id];
}

export function ekitiHealthOverride(id: string): FacilityOverride | undefined {
  return EKITI_HEALTH[id];
}

export function ekitiHotelOverride(id: string): FacilityOverride | undefined {
  return EKITI_HOTELS[id];
}

export function ekitiBillboardOverride(id: string): FacilityOverride | undefined {
  return EKITI_BILLBOARDS[id];
}
