import { COMPANIES, HOTELS } from "./directory";
import type {
  BillboardRecord,
  CctvCamera,
  MarketRecord,
  ProjectRecord,
  TaxLedgerRow,
  VehicleRecord,
} from "./types";

export const VEHICLES: VehicleRecord[] = [
  {
    id: "veh-1",
    plate: "LSD-482-KJ",
    make: "Toyota",
    model: "Camry",
    color: "Black",
    year: 2019,
    ownerName: "Ada Okoro",
    ownerType: "individual",
    state: "Lagos",
    licenceExpiry: "2026-11-12",
    insuranceExpiry: "2026-09-30",
    roadworthinessExpiry: "2026-10-01",
    taxPaid: 18500,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-2",
    plate: "ABC-193-FG",
    make: "Honda",
    model: "Accord",
    color: "Silver",
    year: 2016,
    ownerName: "Chidi Bello",
    ownerType: "individual",
    state: "FCT",
    licenceExpiry: "2025-12-01",
    insuranceExpiry: "2026-01-15",
    roadworthinessExpiry: "2025-08-20",
    taxPaid: 12000,
    taxOwed: 45000,
    status: "expired",
  },
  {
    id: "veh-3",
    plate: "KRD-771-AA",
    make: "Mercedes-Benz",
    model: "E350",
    color: "White",
    year: 2021,
    ownerName: "MTN Nigeria",
    ownerType: "company",
    state: "Lagos",
    licenceExpiry: "2027-03-04",
    insuranceExpiry: "2026-12-31",
    roadworthinessExpiry: "2026-12-31",
    taxPaid: 86000,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-4",
    plate: "RIV-220-QP",
    make: "Toyota",
    model: "Hiace",
    color: "Blue",
    year: 2014,
    ownerName: "Garden City Transport",
    ownerType: "company",
    state: "Rivers",
    licenceExpiry: "2026-02-11",
    insuranceExpiry: "2025-11-09",
    roadworthinessExpiry: "2026-01-02",
    taxPaid: 8000,
    taxOwed: 62000,
    status: "expired",
  },
  {
    id: "veh-5",
    plate: "KN-014-GE",
    make: "Peugeot",
    model: "301",
    color: "Grey",
    year: 2018,
    ownerName: "Amina Yusuf",
    ownerType: "individual",
    state: "Kano",
    licenceExpiry: "2026-08-18",
    insuranceExpiry: "2026-08-18",
    roadworthinessExpiry: "2026-08-18",
    taxPaid: 14000,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-6",
    plate: "OY-558-LM",
    make: "Lexus",
    model: "RX 350",
    color: "Wine",
    year: 2020,
    ownerName: "Premier Hotel Ibadan",
    ownerType: "company",
    state: "Oyo",
    licenceExpiry: "2025-06-22",
    insuranceExpiry: "2025-06-22",
    roadworthinessExpiry: "2025-05-01",
    taxPaid: 0,
    taxOwed: 91000,
    status: "watchlist",
  },
  {
    id: "veh-7",
    plate: "FCT-009-GOV",
    make: "Toyota",
    model: "Land Cruiser",
    color: "White",
    year: 2022,
    ownerName: "FCT Administration",
    ownerType: "government",
    state: "FCT",
    licenceExpiry: "2027-01-01",
    insuranceExpiry: "2027-01-01",
    roadworthinessExpiry: "2027-01-01",
    taxPaid: 0,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-8",
    plate: "LAG-334-TR",
    make: "MAN",
    model: "Truck",
    color: "Yellow",
    year: 2012,
    ownerName: "Dangote Group",
    ownerType: "company",
    state: "Lagos",
    licenceExpiry: "2026-04-09",
    insuranceExpiry: "2026-04-09",
    roadworthinessExpiry: "2026-03-12",
    taxPaid: 210000,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-9",
    plate: "ED-882-BK",
    make: "Kia",
    model: "Rio",
    color: "Red",
    year: 2017,
    ownerName: "Osaze Igbinedion",
    ownerType: "individual",
    state: "Edo",
    licenceExpiry: "2024-12-31",
    insuranceExpiry: "2025-01-31",
    roadworthinessExpiry: "2024-11-20",
    taxPaid: 5000,
    taxOwed: 38000,
    status: "expired",
  },
  {
    id: "veh-10",
    plate: "KD-441-ZX",
    make: "Hyundai",
    model: "Elantra",
    color: "Blue",
    year: 2019,
    ownerName: "Nuhu Sani",
    ownerType: "individual",
    state: "Kaduna",
    licenceExpiry: "2026-09-09",
    insuranceExpiry: "2026-09-09",
    roadworthinessExpiry: "2026-07-01",
    taxPaid: 16000,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-11",
    plate: "APP-101-NG",
    make: "Ford",
    model: "Explorer",
    color: "Black",
    year: 2018,
    ownerName: "Access Bank Plc",
    ownerType: "company",
    state: "Lagos",
    licenceExpiry: "2026-12-12",
    insuranceExpiry: "2026-12-12",
    roadworthinessExpiry: "2026-11-11",
    taxPaid: 54000,
    taxOwed: 0,
    status: "compliant",
  },
  {
    id: "veh-12",
    plate: "PHC-667-MM",
    make: "Nissan",
    model: "Almera",
    color: "White",
    year: 2015,
    ownerName: "Ibinabo Hart",
    ownerType: "individual",
    state: "Rivers",
    licenceExpiry: "2026-01-20",
    insuranceExpiry: "2025-10-04",
    roadworthinessExpiry: "2025-09-15",
    taxPaid: 9000,
    taxOwed: 27000,
    status: "expired",
  },
];

export const CCTV_CAMERAS: CctvCamera[] = [
  { id: "cam-1", name: "Third Mainland Bridge NB", operator: "Lagos Traffic Management", state: "Lagos", city: "Lagos Island", lat: 6.508, lon: 3.399, type: "highway", online: true },
  { id: "cam-2", name: "Lekki-Epe Expressway Toll", operator: "Lagos Traffic Management", state: "Lagos", city: "Lekki", lat: 6.441, lon: 3.528, type: "traffic", online: true },
  { id: "cam-3", name: "Ikeja Computer Village Junction", operator: "Lagos State Command", state: "Lagos", city: "Ikeja", lat: 6.601, lon: 3.348, type: "traffic", online: true },
  { id: "cam-4", name: "Ahmadu Bello Way / Constitution", operator: "FCT Traffic (FRSC/FCTA)", state: "FCT", city: "Central Area", lat: 9.057, lon: 7.495, type: "traffic", online: true },
  { id: "cam-5", name: "Wuse Market Approach", operator: "FCT Administration", state: "FCT", city: "Wuse", lat: 9.069, lon: 7.465, type: "market", online: true },
  { id: "cam-6", name: "Airport Road Gwarinpa", operator: "FCT Traffic", state: "FCT", city: "Gwarinpa", lat: 9.11, lon: 7.41, type: "highway", online: false },
  { id: "cam-7", name: "Kano Murtala Roundabout", operator: "Kano State Traffic", state: "Kano", city: "Kano", lat: 12.002, lon: 8.592, type: "traffic", online: true },
  { id: "cam-8", name: "PH Aba Road / Artillery", operator: "Rivers State Traffic", state: "Rivers", city: "Port Harcourt", lat: 4.824, lon: 7.034, type: "traffic", online: true },
  { id: "cam-9", name: "Ibadan Challenge Junction", operator: "Oyo State Traffic", state: "Oyo", city: "Ibadan", lat: 7.377, lon: 3.947, type: "traffic", online: true },
  { id: "cam-10", name: "Kaduna Stadium Roundabout", operator: "Kaduna Traffic Agency", state: "Kaduna", city: "Kaduna", lat: 10.51, lon: 7.43, type: "traffic", online: true },
  { id: "cam-11", name: "Benin Ring Road", operator: "Edo Traffic Management", state: "Edo", city: "Benin City", lat: 6.335, lon: 5.603, type: "traffic", online: true },
  { id: "cam-12", name: "Eko Hotels Forecourt", operator: "Eko Hotels & Suites", state: "Lagos", city: "Victoria Island", lat: 6.4265, lon: 3.4303, type: "organization", online: true },
  { id: "cam-13", name: "Transcorp Hilton Forecourt", operator: "Transcorp Hilton Abuja", state: "FCT", city: "Maitama", lat: 9.0765, lon: 7.4951, type: "organization", online: true },
  { id: "cam-14", name: "Balogun Market Perimeter", operator: "Lagos Markets Board", state: "Lagos", city: "Lagos Island", lat: 6.455, lon: 3.389, type: "market", online: true },
  { id: "cam-15", name: "Onitsha Main Market Gate", operator: "Anambra Markets Authority", state: "Anambra", city: "Onitsha", lat: 6.145, lon: 6.787, type: "market", online: false },
];

export const BILLBOARDS: BillboardRecord[] = [
  { id: "bb-1", location: "Third Mainland Bridge approach", state: "Lagos", city: "Yaba", operator: "Primedia Outdoor", permitNo: "LASG/BB/2024/1182", permitExpiry: "2026-12-31", taxPaid: 4200000, taxOwed: 0, verification: "verified" },
  { id: "bb-2", location: "Airport Road, Abuja", state: "FCT", city: "Abuja", operator: "Afromedia", permitNo: "FCTA/BB/2025/044", permitExpiry: "2026-06-30", taxPaid: 1800000, taxOwed: 650000, verification: "pending" },
  { id: "bb-3", location: "Aba Road, Port Harcourt", state: "Rivers", city: "Port Harcourt", operator: "Massilia Outdoor", permitNo: "RVSG/BB/2023/901", permitExpiry: "2025-09-01", taxPaid: 400000, taxOwed: 2100000, verification: "flagged" },
  { id: "bb-4", location: "Zaria Road, Kano", state: "Kano", city: "Kano", operator: "Kano Outdoor Ltd", permitNo: "KNSG/BB/2025/210", permitExpiry: "2027-01-15", taxPaid: 960000, taxOwed: 0, verification: "verified" },
  { id: "bb-5", location: "Ring Road, Ibadan", state: "Oyo", city: "Ibadan", operator: "Oyo Signage Agency", permitNo: "OYSG/BB/2024/332", permitExpiry: "2026-08-08", taxPaid: 720000, taxOwed: 0, verification: "verified" },
  { id: "bb-6", location: "Lekki-Epe Expressway", state: "Lagos", city: "Lekki", operator: "Admax Media", permitNo: "LASG/BB/2025/2044", permitExpiry: "2026-03-20", taxPaid: 2500000, taxOwed: 800000, verification: "pending" },
  { id: "bb-7", location: "Independence Way, Kaduna", state: "Kaduna", city: "Kaduna", operator: "Northern Displays", permitNo: "KDSG/BB/2024/077", permitExpiry: "2025-12-12", taxPaid: 0, taxOwed: 1450000, verification: "flagged" },
];

export const MARKETS: MarketRecord[] = [
  { id: "mkt-1", name: "Balogun Market", state: "Lagos", city: "Lagos Island", stalls: 4200, levyPaid: 186000000, levyOwed: 12000000, verification: "verified", hasCctv: true },
  { id: "mkt-2", name: "Computer Village", state: "Lagos", city: "Ikeja", stalls: 1800, levyPaid: 64000000, levyOwed: 0, verification: "verified", hasCctv: true },
  { id: "mkt-3", name: "Wuse Market", state: "FCT", city: "Wuse", stalls: 2500, levyPaid: 41000000, levyOwed: 8500000, verification: "pending", hasCctv: true },
  { id: "mkt-4", name: "Onitsha Main Market", state: "Anambra", city: "Onitsha", stalls: 6500, levyPaid: 210000000, levyOwed: 0, verification: "verified", hasCctv: false },
  { id: "mkt-5", name: "Kurmi Market", state: "Kano", city: "Kano", stalls: 3100, levyPaid: 28000000, levyOwed: 6400000, verification: "verified", hasCctv: true },
  { id: "mkt-6", name: "Mile 1 Market", state: "Rivers", city: "Port Harcourt", stalls: 1600, levyPaid: 19000000, levyOwed: 2200000, verification: "pending", hasCctv: true },
  { id: "mkt-7", name: "Bodija Market", state: "Oyo", city: "Ibadan", stalls: 2200, levyPaid: 17000000, levyOwed: 0, verification: "verified", hasCctv: false },
  { id: "mkt-8", name: "Aba Ariaria Market", state: "Abia", city: "Aba", stalls: 5400, levyPaid: 92000000, levyOwed: 18000000, verification: "flagged", hasCctv: false },
];

export const PROJECTS: ProjectRecord[] = [
  { id: "prj-1", title: "Lagos Blue Line extension works", ministry: "Ministry of Transportation", state: "Lagos", budget: 48000000000, spent: 31200000000, progress: 68, status: "on-track", contractor: "CRCC / LAMATA partners" },
  { id: "prj-2", title: "Abuja CCTV command centre upgrade", ministry: "FCT Administration", state: "FCT", budget: 9200000000, spent: 4100000000, progress: 44, status: "delayed", contractor: "National Security Systems Ltd" },
  { id: "prj-3", title: "Kano–Kaduna highway rehabilitation", ministry: "Federal Ministry of Works", state: "Kano", budget: 126000000000, spent: 54000000000, progress: 39, status: "on-track", contractor: "Julius Berger / FCC" },
  { id: "prj-4", title: "Port Harcourt market lighting & CCTV", ministry: "Rivers Ministry of Commerce", state: "Rivers", budget: 1800000000, spent: 1760000000, progress: 97, status: "completed", contractor: "Garden City Electrics" },
  { id: "prj-5", title: "National hotel verification digitisation", ministry: "Tourism Board / NTDC", state: "FCT", budget: 2400000000, spent: 980000000, progress: 41, status: "on-track", contractor: "My App Civic Systems" },
  { id: "prj-6", title: "Ibadan signage & billboard audit", ministry: "Oyo Signage Agency", state: "Oyo", budget: 640000000, spent: 210000000, progress: 22, status: "flagged", contractor: "OYSG Internal / Admax" },
];

export function taxLedger(): TaxLedgerRow[] {
  const hotelRows: TaxLedgerRow[] = HOTELS.map((h) => ({
    id: `tax-${h.id}`,
    entityType: "hotel",
    entityName: h.name,
    tin: h.tin,
    state: h.state,
    taxPaid: h.taxPaid,
    taxOwed: h.taxOwed,
    lastPayment: "2026-07-15",
  }));
  const companyRows: TaxLedgerRow[] = COMPANIES.map((c) => ({
    id: `tax-${c.id}`,
    entityType: "company",
    entityName: c.name,
    tin: c.tin,
    state: c.state,
    taxPaid: c.taxPaid,
    taxOwed: c.taxOwed,
    lastPayment: "2026-06-30",
  }));
  const vehicleRows: TaxLedgerRow[] = VEHICLES.map((v) => ({
    id: `tax-${v.id}`,
    entityType: "vehicle",
    entityName: `${v.plate} · ${v.ownerName}`,
    state: v.state,
    taxPaid: v.taxPaid,
    taxOwed: v.taxOwed,
    lastPayment: "2026-05-20",
  }));
  const boardRows: TaxLedgerRow[] = BILLBOARDS.map((b) => ({
    id: `tax-${b.id}`,
    entityType: "billboard",
    entityName: b.location,
    state: b.state,
    taxPaid: b.taxPaid,
    taxOwed: b.taxOwed,
    lastPayment: "2026-04-12",
  }));
  const marketRows: TaxLedgerRow[] = MARKETS.map((m) => ({
    id: `tax-${m.id}`,
    entityType: "market",
    entityName: m.name,
    state: m.state,
    taxPaid: m.levyPaid,
    taxOwed: m.levyOwed,
    lastPayment: "2026-08-01",
  }));
  return [...hotelRows, ...companyRows, ...vehicleRows, ...boardRows, ...marketRows];
}

export function papersExpired(vehicle: VehicleRecord, asOf = new Date()) {
  const days = (iso: string) => new Date(iso).getTime() < asOf.getTime();
  return {
    licence: days(vehicle.licenceExpiry),
    insurance: days(vehicle.insuranceExpiry),
    roadworthiness: days(vehicle.roadworthinessExpiry),
  };
}

export function lookupPlate(plate: string) {
  const normalised = plate.replace(/\s+/g, "").toUpperCase();
  return VEHICLES.find((v) => v.plate.replace(/\s+/g, "").toUpperCase() === normalised);
}
