import type { BlogPost, Booking, Property } from "./types";

const owners = {
  ada: {
    id: "owner-1",
    firstName: "Ada",
    lastName: "Okoro",
    email: "ada@myapp.ng",
    phone: "+234 801 234 5678",
    companyName: "Okoro Homes",
  },
  chidi: {
    id: "owner-2",
    firstName: "Chidi",
    lastName: "Bello",
    email: "chidi@myapp.ng",
    phone: "+234 802 345 6789",
    companyName: "Bello Shortlets",
  },
  amina: {
    id: "owner-3",
    firstName: "Amina",
    lastName: "Yusuf",
    email: "amina@myapp.ng",
    phone: "+234 803 456 7890",
    companyName: "Capital Stays",
  },
} as const;

export const PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "lekki-phase-1-serviced-apartment",
    title: "Lekki Phase 1 Serviced Apartment",
    description:
      "Bright 2-bedroom serviced apartment in Lekki Phase 1 with fast Wi‑Fi, 24/7 power, and secure estate access. Ideal for short stays and business trips.",
    propertyType: "Apartment",
    listingCategory: "Shortlet",
    price: 85000,
    pricePer: "night",
    images: [
      "/listings/stay-1.jpg",
      "/listings/stay-2.jpg",
      "/listings/stay-3.jpg",
    ],
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Maximum Security",
      "24/7 Power",
      "Kitchen",
      "Air Conditioning",
      "Balcony",
      "Laundry",
    ],
    location: {
      address: "Admiralty Way",
      city: "Lekki",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.ada,
    rating: 4.8,
    reviewsCount: 42,
    hasHourlyReservation: true,
    whatsappNumber: "2348012345678",
    status: "active",
    createdAt: "2025-11-12",
  },
  {
    id: "2",
    slug: "victoria-island-waterfront-hotel-suite",
    title: "Victoria Island Waterfront Hotel Suite",
    description:
      "Premium hotel suite overlooking the lagoon with room service, gym access, and flexible hourly booking options.",
    propertyType: "Hotel",
    listingCategory: "Shortlet",
    price: 160000,
    pricePer: "night",
    images: [
      "/listings/stay-4.jpg",
      "/listings/hotel-1.jpg",
      "/listings/hotel-2.jpg",
    ],
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Air Conditioning",
      "Kitchen",
      "Maximum Security",
      "24/7 Power",
    ],
    location: {
      address: "Ahmadu Bello Way",
      city: "Victoria Island",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.chidi,
    rating: 4.6,
    reviewsCount: 28,
    hasHourlyReservation: true,
    whatsappNumber: "2348023456789",
    status: "active",
    createdAt: "2025-10-02",
  },
  {
    id: "3",
    slug: "ikoyi-luxury-3-bed-shortlet",
    title: "Ikoyi Luxury 3-Bed Shortlet",
    description:
      "Spacious 3-bedroom shortlet in a gated Ikoyi community with smart TVs, kitchenette, and dedicated parking.",
    propertyType: "Serviced",
    listingCategory: "Shortlet",
    price: 220000,
    pricePer: "night",
    images: [
      "/listings/hotel-3.jpg",
      "/listings/hotel-4.jpg",
      "/listings/stay-1.jpg",
    ],
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Maximum Security",
      "24/7 Power",
      "Kitchen",
      "Air Conditioning",
      "Balcony",
      "Laundry",
    ],
    location: {
      address: "Awolowo Road",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.ada,
    rating: 4.9,
    reviewsCount: 61,
    hasHourlyReservation: false,
    whatsappNumber: "2348012345678",
    status: "active",
    createdAt: "2025-09-18",
  },
  {
    id: "4",
    slug: "maitama-executive-apartment",
    title: "Maitama Executive Apartment",
    description:
      "Quiet executive apartment in Maitama with workspace, reliable power, and easy access to Wuse and the CBD.",
    propertyType: "Apartment",
    listingCategory: "Shortlet",
    price: 120000,
    pricePer: "night",
    images: [
      "/listings/stay-2.jpg",
      "/listings/stay-3.jpg",
      "/listings/stay-4.jpg",
    ],
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Kitchen",
      "Air Conditioning",
      "24/7 Power",
      "Maximum Security",
    ],
    location: {
      address: "Aguiyi Ironsi Street",
      city: "Maitama",
      state: "Abuja",
      country: "Nigeria",
    },
    owner: owners.amina,
    rating: 4.7,
    reviewsCount: 33,
    hasHourlyReservation: true,
    whatsappNumber: "2348034567890",
    status: "active",
    createdAt: "2025-12-01",
  },
  {
    id: "5",
    slug: "gwarinpa-family-resort-villa",
    title: "Gwarinpa Family Resort Villa",
    description:
      "Family-friendly resort-style villa with outdoor seating, full kitchen, and flexible multi-night rates.",
    propertyType: "Resort",
    listingCategory: "Shortlet",
    price: 310000,
    pricePer: "night",
    images: [
      "/listings/hotel-1.jpg",
      "/listings/hotel-2.jpg",
      "/listings/hotel-3.jpg",
    ],
    bedrooms: 5,
    bathrooms: 4,
    maxGuests: 10,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Kitchen",
      "Air Conditioning",
      "Balcony",
      "Laundry",
      "Maximum Security",
      "24/7 Power",
    ],
    location: {
      address: "1st Avenue",
      city: "Gwarinpa",
      state: "Abuja",
      country: "Nigeria",
    },
    owner: owners.amina,
    rating: 4.5,
    reviewsCount: 19,
    hasHourlyReservation: false,
    whatsappNumber: "2348034567890",
    status: "active",
    createdAt: "2025-08-22",
  },
  {
    id: "6",
    slug: "surulere-studio-short-stay",
    title: "Surulere Studio Short Stay",
    description:
      "Compact, clean studio near shops and transit. Perfect for solo travelers and weekend getaways.",
    propertyType: "Apartment",
    listingCategory: "Shortlet",
    price: 45000,
    pricePer: "night",
    images: [
      "/listings/hotel-4.jpg",
      "/listings/stay-1.jpg",
    ],
    bedrooms: 0,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["Fast Wifi (50 Mbps)", "Kitchen", "Air Conditioning", "24/7 Power"],
    location: {
      address: "Adeniran Ogunsanya",
      city: "Surulere",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.chidi,
    rating: 4.3,
    reviewsCount: 15,
    hasHourlyReservation: true,
    whatsappNumber: "2348023456789",
    status: "active",
    createdAt: "2026-01-05",
  },
  {
    id: "7",
    slug: "wuse-2-business-apartment",
    title: "Wuse 2 Business Apartment",
    description:
      "Modern apartment tailored for business travelers with desk space, laundry, and secure parking.",
    propertyType: "Serviced",
    listingCategory: "Shortlet",
    price: 95000,
    pricePer: "night",
    images: [
      "/listings/stay-2.jpg",
      "/listings/stay-3.jpg",
    ],
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Kitchen",
      "Laundry",
      "Air Conditioning",
      "Maximum Security",
    ],
    location: {
      address: "Aminu Kano Crescent",
      city: "Wuse",
      state: "Abuja",
      country: "Nigeria",
    },
    owner: owners.amina,
    rating: 4.4,
    reviewsCount: 22,
    hasHourlyReservation: true,
    whatsappNumber: "2348034567890",
    status: "active",
    createdAt: "2025-07-14",
  },
  {
    id: "8",
    slug: "banana-island-penthouse-for-sale",
    title: "Banana Island Penthouse for Sale",
    description:
      "Signature penthouse with panoramic lagoon views, private elevator lobby, and premium finishes throughout.",
    propertyType: "Penthouse",
    listingCategory: "Buy",
    price: 850000000,
    pricePer: "total",
    images: [
      "/listings/stay-4.jpg",
      "/listings/hotel-1.jpg",
      "/listings/hotel-2.jpg",
    ],
    bedrooms: 4,
    bathrooms: 5,
    maxGuests: 8,
    amenities: [
      "Maximum Security",
      "24/7 Power",
      "Kitchen",
      "Air Conditioning",
      "Balcony",
      "Laundry",
    ],
    location: {
      address: "Banana Island",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.ada,
    rating: 4.9,
    reviewsCount: 8,
    hasHourlyReservation: false,
    whatsappNumber: "2348012345678",
    status: "active",
    createdAt: "2025-06-30",
  },
  {
    id: "9",
    slug: "lekki-4-bedroom-detached-house",
    title: "Lekki 4-Bedroom Detached House",
    description:
      "Brand-new detached house in a secured Lekki estate with BQ, fitted kitchen, and ample parking.",
    propertyType: "House",
    listingCategory: "Buy",
    price: 280000000,
    pricePer: "total",
    images: [
      "/listings/hotel-3.jpg",
      "/listings/hotel-4.jpg",
    ],
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 8,
    amenities: ["Maximum Security", "24/7 Power", "Kitchen", "Balcony", "Laundry"],
    location: {
      address: "Chevron Drive",
      city: "Lekki",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.chidi,
    rating: 4.6,
    reviewsCount: 11,
    hasHourlyReservation: false,
    whatsappNumber: "2348023456789",
    status: "active",
    createdAt: "2025-05-21",
  },
  {
    id: "10",
    slug: "asokoro-modern-villa",
    title: "Asokoro Modern Villa",
    description:
      "Elegant villa in Asokoro with landscaped gardens, smart home features, and premium fittings.",
    propertyType: "Villa",
    listingCategory: "Buy",
    price: 450000000,
    pricePer: "total",
    images: [
      "/listings/stay-1.jpg",
      "/listings/stay-2.jpg",
    ],
    bedrooms: 5,
    bathrooms: 5,
    maxGuests: 10,
    amenities: [
      "Maximum Security",
      "24/7 Power",
      "Kitchen",
      "Air Conditioning",
      "Balcony",
      "Laundry",
    ],
    location: {
      address: "Yakubu Gowon Crescent",
      city: "Abuja",
      state: "Abuja",
      country: "Nigeria",
    },
    owner: owners.amina,
    rating: 4.8,
    reviewsCount: 6,
    hasHourlyReservation: false,
    whatsappNumber: "2348034567890",
    status: "active",
    createdAt: "2025-04-10",
  },
  {
    id: "11",
    slug: "victoria-island-office-apartment-rent",
    title: "Victoria Island Office Apartment",
    description:
      "Long-term serviced apartment suitable for professionals. Includes cleaning, power, and security.",
    propertyType: "Serviced",
    listingCategory: "Rent",
    price: 6500000,
    pricePer: "year",
    images: [
      "/listings/stay-3.jpg",
      "/listings/stay-4.jpg",
    ],
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: [
      "Fast Wifi (50 Mbps)",
      "Kitchen",
      "Air Conditioning",
      "24/7 Power",
      "Maximum Security",
      "Laundry",
    ],
    location: {
      address: "Adeola Odeku",
      city: "Victoria Island",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.ada,
    rating: 4.5,
    reviewsCount: 17,
    hasHourlyReservation: false,
    whatsappNumber: "2348012345678",
    status: "active",
    createdAt: "2025-03-08",
  },
  {
    id: "12",
    slug: "yaba-1-bed-apartment-rent",
    title: "Yaba 1-Bed Apartment for Rent",
    description:
      "Affordable 1-bedroom apartment near tech hubs and campuses. Water, security, and prepaid meter included.",
    propertyType: "Apartment",
    listingCategory: "Rent",
    price: 1800000,
    pricePer: "year",
    images: [
      "/listings/hotel-1.jpg",
      "/listings/hotel-2.jpg",
    ],
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["Kitchen", "Maximum Security", "24/7 Power"],
    location: {
      address: "Herbert Macaulay Way",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    owner: owners.chidi,
    rating: 4.2,
    reviewsCount: 9,
    hasHourlyReservation: false,
    whatsappNumber: "2348023456789",
    status: "active",
    createdAt: "2025-02-15",
  },
  {
    id: "13",
    slug: "jabi-3-bed-flat-rent",
    title: "Jabi 3-Bed Flat for Rent",
    description:
      "Well-kept 3-bedroom flat close to Jabi Lake Mall with parking and steady power backup.",
    propertyType: "Apartment",
    listingCategory: "Rent",
    price: 4200000,
    pricePer: "year",
    images: [
      "/listings/hotel-3.jpg",
      "/listings/hotel-4.jpg",
    ],
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    amenities: ["Kitchen", "Air Conditioning", "24/7 Power", "Maximum Security", "Balcony"],
    location: {
      address: "Jabi District",
      city: "Abuja",
      state: "Abuja",
      country: "Nigeria",
    },
    owner: owners.amina,
    rating: 4.4,
    reviewsCount: 13,
    hasHourlyReservation: false,
    whatsappNumber: "2348034567890",
    status: "active",
    createdAt: "2025-01-28",
  },
  {
    id: "14",
    slug: "ibadan-garden-house-rent",
    title: "Ibadan Garden House for Rent",
    description:
      "Peaceful house with a private garden, ideal for families relocating to Ibadan.",
    propertyType: "House",
    listingCategory: "Rent",
    price: 2500000,
    pricePer: "year",
    images: [
      "/listings/stay-1.jpg",
      "/listings/stay-2.jpg",
    ],
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    amenities: ["Kitchen", "Balcony", "Maximum Security", "24/7 Power"],
    location: {
      address: "Bodija",
      city: "Ibadan",
      state: "Oyo",
      country: "Nigeria",
    },
    owner: owners.ada,
    rating: 4.1,
    reviewsCount: 5,
    hasHourlyReservation: false,
    whatsappNumber: "2348012345678",
    status: "active",
    createdAt: "2024-12-12",
  },
  {
    id: "15",
    slug: "akure-city-hotel-rooms",
    title: "Akure City Hotel Rooms",
    description:
      "Comfortable hotel rooms in the heart of Akure with restaurant access and hourly options.",
    propertyType: "Hotel",
    listingCategory: "Shortlet",
    price: 38000,
    pricePer: "night",
    images: [
      "/listings/stay-3.jpg",
      "/listings/stay-4.jpg",
    ],
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["Fast Wifi (50 Mbps)", "Air Conditioning", "24/7 Power", "Maximum Security"],
    location: {
      address: "Oba Adesida Road",
      city: "Akure",
      state: "Ondo",
      country: "Nigeria",
    },
    owner: owners.chidi,
    rating: 4.0,
    reviewsCount: 12,
    hasHourlyReservation: true,
    whatsappNumber: "2348023456789",
    status: "active",
    createdAt: "2024-11-03",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "short-let-rentals-lagos-top-10-areas",
    title:
      "Experience the Dynamic Charm of Short-let Rentals in Lagos: Top 10 Areas to Explore",
    description:
      "Here are the top best locations of shortlets you can explore in lagos...",
    date: "May 10 2025",
    category: "Short-let",
    image: "/Blog1-image.jpg",
    content: [
      "Lagos remains Nigeria’s busiest short-let market, with demand concentrated in Lekki, Victoria Island, Ikoyi, and Surulere.",
      "Travelers look for reliable power, fast Wi‑Fi, and secure estates—so listings that highlight those amenities convert faster.",
      "If you are listing a shortlet, clear photos, accurate pricing, and direct contact details help guests reach you without friction.",
    ],
  },
  {
    slug: "abuja-hotels-guest-houses-or-shortlets",
    title: "Which has more demand in Abuja? Hotels, Guest house or shortlets.",
    description:
      "Here are the top best locations of shortlets you can explore in lagos...",
    date: "May 10 2025",
    category: "Short-let",
    image: "/Blog2-image.jpg",
    content: [
      "Abuja demand shifts with conferences, government calendars, and family visits.",
      "Shortlets in Maitama, Wuse, and Gwarinpa compete strongly with hotels when they offer kitchens and weekly rates.",
      "Guest houses still win for budget stays—but premium shortlets capture longer business trips.",
    ],
  },
  {
    slug: "real-estate-investment-nigeria-major-cities",
    title: "Top Real Estate Investment Opportunities in Nigeria's Major Cities",
    description:
      "Discover the best real estate investment opportunities across Nigeria's thriving markets...",
    date: "May 8 2025",
    category: "Investment",
    image: "/Blog1-image.jpg",
    content: [
      "Lagos and Abuja continue to lead investment interest for both sales and short-let yield strategies.",
      "Investors increasingly prefer verified listings with transparent agent contacts and clear title information.",
      "Secondary cities like Ibadan and Akure are gaining attention for rental yield at lower entry prices.",
    ],
  },
  {
    slug: "guide-renting-lagos-abuja",
    title: "A Complete Guide to Renting Properties in Lagos and Abuja",
    description:
      "Everything you need to know about renting properties in Nigeria's most popular cities...",
    date: "May 5 2025",
    category: "Rent",
    image: "/Blog2-image.jpg",
    content: [
      "Renting in Lagos and Abuja usually involves agency fees, caution deposits, and clear inspection schedules.",
      "Always confirm utilities, estate rules, and who pays service charges before signing.",
      "My App helps you browse verified rentals and contact agents directly.",
    ],
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    propertyId: "1",
    propertyTitle: "Lekki Phase 1 Serviced Apartment",
    image:
      "/listings/hotel-1.jpg",
    location: "Lekki, Lagos",
    checkIn: "2026-09-02",
    checkOut: "2026-09-05",
    status: "upcoming",
    total: "₦255,000",
  },
  {
    id: "b2",
    propertyId: "4",
    propertyTitle: "Maitama Executive Apartment",
    image:
      "/listings/hotel-2.jpg",
    location: "Maitama, Abuja",
    checkIn: "2026-06-10",
    checkOut: "2026-06-12",
    status: "past",
    total: "₦240,000",
  },
  {
    id: "b3",
    propertyId: "2",
    propertyTitle: "Victoria Island Waterfront Hotel Suite",
    image:
      "/listings/hotel-3.jpg",
    location: "Victoria Island, Lagos",
    checkIn: "2026-04-01",
    checkOut: "2026-04-03",
    status: "canceled",
    total: "₦320,000",
  },
];

export const LOCATIONS = [
  { city: "Lagos", image: "/Lagos-Image.jpg", hasTag: false },
  { city: "Abuja", image: "/Abuja-image.jpg", hasTag: true },
  { city: "Akure", image: "/Akure-image.jpg", hasTag: false },
  { city: "Ibadan", image: "/Ibadab-Image.jpg", hasTag: false },
  { city: "Abia", image: "/Abia-image.jpg", hasTag: false },
] as const;

export const PROPERTY_TYPES = [
  {
    title: "Hotels",
    image: "/Hotel-image.jpg",
    description: "Premium rooms and suites for short stays.",
  },
  {
    title: "Apartments",
    image: "/Apartment-image.jpg",
    description: "Comfortable flats for work and leisure.",
  },
  {
    title: "Resorts",
    image: "/Resort-image.jpg",
    description: "Spacious getaways with standout amenities.",
  },
] as const;

export const BRAND_NAME = "USSAP";
export const BRAND_FULL_NAME = "Unified Smart Spatial Addressing Platform";
