import { encodeGrid } from "./geocode";
import type {
  ProjectSite,
  ResidentialSite,
  SchoolSite,
  TelecomSite,
  TrafficSite,
  UssapSite,
} from "./types";

const now = "2026-08-26T10:00:00.000Z";

function base(
  lat: number,
  lng: number,
  label: string,
  state: string,
  city: string,
  extra: Partial<UssapSite> = {},
) {
  return {
    code: encodeGrid(lat, lng, 8),
    lat,
    lng,
    label,
    state,
    city,
    verification: "verified" as const,
    sensitivity: "public" as const,
    createdAt: now,
    updatedAt: now,
    ...extra,
  };
}

export const TELECOM_SITES: TelecomSite[] = [
  {
    ...base(6.4474, 3.4722, "9mobile Lekki Cell Site", "Lagos", "Lekki"),
    sector: "telecom",
    towerId: "9MO-LAG-LEK-088",
    operator: "9mobile",
    technology: ["4G"],
    heightM: 32,
    equipment: [{ name: "RRU", model: "Ericsson Radio" }],
    lastMaintenance: "2026-05-20",
    nextMaintenance: "2026-08-20",
    maintenanceRouteId: "ROUTE-LAG-EAST-B",
    image: "/facilities/telecom/telecom-001.jpg",
  },
  {
    ...base(6.4282, 3.4219, "MTN Victoria Island Rooftop", "Lagos", "Victoria Island"),
    sector: "telecom",
    towerId: "MTN-LAG-VI-022",
    operator: "MTN Nigeria",
    technology: ["4G", "5G"],
    heightM: 28,
    equipment: [{ name: "Small cell", model: "Nokia Flexi" }],
    lastMaintenance: "2026-07-01",
    nextMaintenance: "2026-10-01",
    maintenanceRouteId: "ROUTE-LAG-ISLAND",
    image: "/facilities/telecom/telecom-002.jpg",
  },
  {
    ...base(9.0579, 7.4951, "Airtel Maitama Macro Site", "FCT", "Maitama"),
    sector: "telecom",
    towerId: "AIR-FCT-MAI-011",
    operator: "Airtel Nigeria",
    technology: ["4G"],
    heightM: 40,
    equipment: [{ name: "Antenna", model: "Kathrein 800" }],
    lastMaintenance: "2026-06-15",
    nextMaintenance: "2026-09-15",
    maintenanceRouteId: "ROUTE-FCT-MAITAMA",
    image: "/facilities/telecom/telecom-003.jpg",
  },
  {
    ...base(6.5244, 3.3792, "MTN Ikeja Macro Tower", "Lagos", "Ikeja", {
      sensitivity: "restricted",
      ownerOrg: "MTN Nigeria",
    }),
    sector: "telecom",
    towerId: "MTN-LAG-IKJ-014",
    operator: "MTN Nigeria",
    technology: ["4G", "5G"],
    heightM: 45,
    equipment: [
      { name: "RRU", model: "Huawei 5900", serial: "HW-5900-014" },
      { name: "Antenna", model: "Kathrein 80010692" },
    ],
    lastMaintenance: "2026-07-12",
    nextMaintenance: "2026-10-12",
    maintenanceRouteId: "ROUTE-LAG-WEST-A",
    image: "/facilities/telecom/telecom-004.jpg",
  },
  {
    ...base(9.0765, 7.3986, "Airtel Abuja CBD Tower", "FCT", "Central Business District", {
      sensitivity: "restricted",
      ownerOrg: "Airtel Nigeria",
    }),
    sector: "telecom",
    towerId: "AIR-FCT-CBD-003",
    operator: "Airtel Nigeria",
    technology: ["4G", "5G"],
    heightM: 52,
    equipment: [{ name: "BBU", model: "Nokia AirScale", serial: "NK-AS-003" }],
    lastMaintenance: "2026-06-01",
    nextMaintenance: "2026-09-01",
    maintenanceRouteId: "ROUTE-FCT-CENTRAL",
    image: "/facilities/telecom/telecom-005.jpg",
  },
  {
    ...base(4.8156, 7.0498, "Glo Port Harcourt Fibre Hub", "Rivers", "Port Harcourt", {
      sensitivity: "classified",
      ownerOrg: "Globacom",
    }),
    sector: "telecom",
    towerId: "GLO-RIV-PH-021",
    operator: "Globacom",
    technology: ["Fibre", "4G"],
    heightM: 38,
    equipment: [{ name: "OLT", model: "ZTE C600" }],
    lastMaintenance: "2026-08-01",
    nextMaintenance: "2026-11-01",
    image: "/facilities/telecom/telecom-006.jpg",
  },
  {
    ...base(7.3775, 3.947, "MTN Ibadan Ring Road Tower", "Oyo", "Ibadan"),
    sector: "telecom",
    towerId: "MTN-OYO-IBD-031",
    operator: "MTN Nigeria",
    technology: ["4G"],
    heightM: 42,
    equipment: [{ name: "RRU", model: "Ericsson AIR 6449" }],
    lastMaintenance: "2026-04-18",
    nextMaintenance: "2026-07-18",
    maintenanceRouteId: "ROUTE-SW-IBADAN",
    image: "/facilities/telecom/telecom-007.jpg",
  },
  {
    ...base(12.0022, 8.592, "Airtel Kano Industrial Site", "Kano", "Kano"),
    sector: "telecom",
    towerId: "AIR-KAN-IND-019",
    operator: "Airtel Nigeria",
    technology: ["4G", "5G"],
    heightM: 48,
    equipment: [
      { name: "Antenna", model: "CommScope VVSSP" },
      { name: "BBU", model: "Huawei BBU5900" },
    ],
    lastMaintenance: "2026-05-05",
    nextMaintenance: "2026-08-05",
    maintenanceRouteId: "ROUTE-NW-KANO",
    image: "/facilities/telecom/telecom-008.jpg",
  },
  {
    ...base(6.335, 5.6037, "Glo Benin City Macro", "Edo", "Benin City"),
    sector: "telecom",
    towerId: "GLO-EDO-BNC-008",
    operator: "Globacom",
    technology: ["4G"],
    heightM: 36,
    equipment: [{ name: "RRU", model: "ZTE R8862" }],
    lastMaintenance: "2026-06-22",
    nextMaintenance: "2026-09-22",
    maintenanceRouteId: "ROUTE-SS-BENIN",
    image: "/facilities/telecom/telecom-009.jpg",
  },
  {
    ...base(5.1036, 7.3506, "9mobile Uyo Campus Site", "Akwa Ibom", "Uyo"),
    sector: "telecom",
    towerId: "9MO-AKI-UYO-012",
    operator: "9mobile",
    technology: ["4G"],
    heightM: 30,
    equipment: [{ name: "Small cell", model: "Ericsson Radio 4408" }],
    lastMaintenance: "2026-03-30",
    nextMaintenance: "2026-06-30",
    maintenanceRouteId: "ROUTE-SS-UYO",
    image: "/facilities/telecom/telecom-010.jpg",
  },
  {
    ...base(6.6018, 3.3515, "MTN Yaba Rooftop 5G", "Lagos", "Yaba", {
      sensitivity: "restricted",
      ownerOrg: "MTN Nigeria",
    }),
    sector: "telecom",
    towerId: "MTN-LAG-YAB-055",
    operator: "MTN Nigeria",
    technology: ["5G", "4G"],
    heightM: 24,
    equipment: [
      { name: "Massive MIMO", model: "Nokia AEHC", serial: "NK-AEHC-055" },
      { name: "Small cell", model: "Nokia Flexi Zone" },
    ],
    lastMaintenance: "2026-08-10",
    nextMaintenance: "2026-11-10",
    maintenanceRouteId: "ROUTE-LAG-MAINLAND",
    image: "/facilities/telecom/telecom-011.jpg",
  },
  {
    ...base(9.8965, 8.8583, "Airtel Jos Plateau Tower", "Plateau", "Jos"),
    sector: "telecom",
    towerId: "AIR-PLT-JOS-007",
    operator: "Airtel Nigeria",
    technology: ["4G"],
    heightM: 44,
    equipment: [{ name: "Antenna", model: "Kathrein 80010764" }],
    lastMaintenance: "2026-05-28",
    nextMaintenance: "2026-08-28",
    maintenanceRouteId: "ROUTE-NC-JOS",
    image: "/facilities/telecom/telecom-012.jpg",
  },
  {
    ...base(11.831, 13.151, "Glo Maiduguri Coverage Mast", "Borno", "Maiduguri", {
      sensitivity: "restricted",
      ownerOrg: "Globacom",
    }),
    sector: "telecom",
    towerId: "GLO-BOR-MAI-004",
    operator: "Globacom",
    technology: ["4G", "3G"],
    heightM: 50,
    equipment: [{ name: "RRU", model: "Huawei AAU5613", serial: "HW-AAU-004" }],
    lastMaintenance: "2026-07-20",
    nextMaintenance: "2026-10-20",
    maintenanceRouteId: "ROUTE-NE-MAID",
    image: "/facilities/telecom/telecom-013.jpg",
  },
  {
    ...base(6.4541, 3.3947, "MTN Lagos Island Macro", "Lagos", "Lagos Island"),
    sector: "telecom",
    towerId: "MTN-LAG-ISL-009",
    operator: "MTN Nigeria",
    technology: ["4G", "5G"],
    heightM: 35,
    equipment: [{ name: "RRU", model: "Ericsson Radio 8823" }],
    lastMaintenance: "2026-06-08",
    nextMaintenance: "2026-09-08",
    maintenanceRouteId: "ROUTE-LAG-ISLAND",
    image: "/facilities/telecom/telecom-014.jpg",
  },
  {
    ...base(7.1608, 3.3481, "9mobile Abeokuta Highway Site", "Ogun", "Abeokuta"),
    sector: "telecom",
    towerId: "9MO-OGN-ABK-016",
    operator: "9mobile",
    technology: ["4G"],
    heightM: 41,
    equipment: [{ name: "Antenna", model: "Huawei AQU4518R24" }],
    lastMaintenance: "2026-04-02",
    nextMaintenance: "2026-07-02",
    maintenanceRouteId: "ROUTE-SW-OGUN",
    image: "/facilities/telecom/telecom-015.jpg",
  },
  {
    ...base(7.6271, 5.2298, "MTN Ado-Ekiti Macro Tower · Adebayo Road", "Ekiti", "Ado Ekiti"),
    sector: "telecom",
    towerId: "MTN-EKI-ADO-024",
    operator: "MTN Nigeria",
    technology: ["4G", "5G"],
    heightM: 43,
    equipment: [{ name: "RRU", model: "Ericsson Radio 8823" }],
    lastMaintenance: "2026-05-14",
    nextMaintenance: "2026-08-14",
    maintenanceRouteId: "ROUTE-SW-EKITI",
    image: "/facilities/telecom/telecom-016.jpg",
  },
  {
    ...base(7.4978, 5.2321, "Airtel Ikere-Ekiti Tower · Old Garage Road", "Ekiti", "Ikere"),
    sector: "telecom",
    towerId: "AIR-EKI-IKR-011",
    operator: "Airtel Nigeria",
    technology: ["4G"],
    heightM: 40,
    equipment: [{ name: "Antenna", model: "Kathrein 80010692" }],
    lastMaintenance: "2026-06-20",
    nextMaintenance: "2026-09-20",
    maintenanceRouteId: "ROUTE-SW-EKITI",
    image: "/facilities/telecom/telecom-017.jpg",
  },
  {
    ...base(7.6084, 5.2262, "Glo Ado Poly Road Site · Ilawe Road junction", "Ekiti", "Ado Ekiti"),
    sector: "telecom",
    towerId: "GLO-EKI-ADO-007",
    operator: "Globacom",
    technology: ["4G"],
    heightM: 38,
    equipment: [{ name: "RRU", model: "Huawei RRU5904" }],
    lastMaintenance: "2026-04-08",
    nextMaintenance: "2026-07-08",
    maintenanceRouteId: "ROUTE-SW-EKITI",
    image: "/facilities/telecom/telecom-018.jpg",
  },
  {
    ...base(7.7941, 5.3372, "9mobile Oye Rural Coverage · Oye-Ikole Road", "Ekiti", "Oye"),
    sector: "telecom",
    towerId: "9MO-EKI-OYE-005",
    operator: "9mobile",
    technology: ["4G", "3G"],
    heightM: 36,
    equipment: [{ name: "Small cell", model: "Ericsson Radio 4408" }],
    lastMaintenance: "2026-03-18",
    nextMaintenance: "2026-06-18",
    maintenanceRouteId: "ROUTE-SW-EKITI",
    image: "/facilities/telecom/telecom-019.jpg",
  },
];

export const PROJECT_SITES: ProjectSite[] = [
  {
    ...base(6.508, 3.399, "Lagos Blue Line Extension Site", "Lagos", "Lagos Island", {
      ownerOrg: "LAMATA",
      sensitivity: "restricted",
    }),
    sector: "project",
    projectCode: "PRJ-LAG-BLU-EXT",
    ministry: "Ministry of Transportation",
    contractor: "CRCC / LAMATA partners",
    progress: 68,
    status: "active",
    media: [
      {
        id: "m1",
        type: "photo",
        url: "/listings/company-1.jpg",
        caption: "Track bed progress — pier 12",
        lat: 6.5081,
        lng: 3.3992,
        capturedAt: "2026-08-20T09:30:00.000Z",
        uploadedBy: "pm@ussap.ng",
      },
    ],
  },
  {
    ...base(9.057, 7.495, "Abuja CCTV Command Centre Upgrade", "FCT", "Central Area", {
      ownerOrg: "FCT Administration",
      sensitivity: "classified",
    }),
    sector: "project",
    projectCode: "PRJ-FCT-CCTV-01",
    ministry: "FCT Administration",
    contractor: "National Security Systems Ltd",
    progress: 44,
    status: "delayed",
    media: [],
  },
  {
    ...base(7.8482, 5.1824, "Ekiti Rural PHC Electrification", "Ekiti", "Ido-Ekiti", {
      ownerOrg: "Ekiti Ministry of Health",
    }),
    sector: "project",
    projectCode: "PRJ-EKI-PHC-04",
    ministry: "Ekiti Ministry of Health",
    contractor: "Ekiti Rural Health Partners",
    progress: 38,
    status: "active",
    media: [],
  },
];

export const TRAFFIC_SITES: TrafficSite[] = [
  {
    ...base(6.508, 3.399, "Third Mainland Bridge NB Camera", "Lagos", "Lagos Island"),
    sector: "traffic",
    siteType: "camera",
    operator: "Lagos Traffic Management",
    statusTag: "online",
    realtimeNote: "Flow normal · 62 km/h avg",
  },
  {
    ...base(6.441, 3.528, "Lekki–Epe Toll Congestion Hotspot", "Lagos", "Lekki"),
    sector: "traffic",
    siteType: "congestion",
    operator: "Lagos Traffic Management",
    statusTag: "congested",
    realtimeNote: "Peak delay +28 min westbound",
  },
  {
    ...base(9.069, 7.465, "Wuse Market Approach Camera", "FCT", "Wuse"),
    sector: "traffic",
    siteType: "monitoring_post",
    operator: "FCT Traffic",
    statusTag: "clear",
  },
  {
    ...base(6.455, 3.389, "CMS Accident-Prone Zone", "Lagos", "Lagos Island"),
    sector: "traffic",
    siteType: "accident_zone",
    operator: "FRSC Lagos",
    statusTag: "incident",
    realtimeNote: "Historical blackspot · enhanced patrol",
  },
  {
    ...base(7.6218, 5.2194, "Fajuyi Roundabout Traffic Camera", "Ekiti", "Ado Ekiti"),
    sector: "traffic",
    siteType: "camera",
    operator: "Ekiti State Traffic Management",
    statusTag: "clear",
    realtimeNote: "Flow normal · Ado township",
  },
];

export const SCHOOL_SITES: SchoolSite[] = [
  {
    ...base(6.5244, 3.3792, "Lagos State Model College Ikeja", "Lagos", "Ikeja"),
    sector: "school",
    schoolType: "secondary",
    ownership: "public",
    enrollment: 2400,
    emergencyContact: "+234 801 200 1001",
  },
  {
    ...base(9.0579, 7.4951, "Government Secondary School Garki", "FCT", "Garki"),
    sector: "school",
    schoolType: "secondary",
    ownership: "public",
    enrollment: 1800,
    emergencyContact: "+234 809 300 2002",
  },
  {
    ...base(7.3775, 3.947, "University of Ibadan Main Gate", "Oyo", "Ibadan"),
    sector: "school",
    schoolType: "tertiary",
    ownership: "public",
    enrollment: 35000,
    emergencyContact: "+234 805 400 3003",
  },
];

export const RESIDENTIAL_SITES: ResidentialSite[] = [
  {
    ...base(6.4474, 3.4722, "Lekki Phase 1 Residence · Plot 14", "Lagos", "Lekki", {
      ownerOrg: "Private homeowner",
    }),
    sector: "residential",
    propertyType: "house",
    unitNo: "Plot 14",
    utilityMeterId: "EKEDC-LP1-88421",
    deliveryNotes: "Blue gate · ring twice",
    shareable: true,
  },
  {
    ...base(9.078, 7.483, "Maitama Avenue Apartment 5B", "FCT", "Maitama"),
    sector: "residential",
    propertyType: "apartment",
    unitNo: "5B",
    utilityMeterId: "AEDC-MAI-22109",
    deliveryNotes: "Use visitor lobby",
    shareable: true,
  },
  {
    ...base(6.5244, 3.3792, "Ikeja GRA Compound Unit C2", "Lagos", "Ikeja"),
    sector: "residential",
    propertyType: "compound",
    unitNo: "C2",
    shareable: false,
    verification: "pending",
  },
];

export function allSites(): UssapSite[] {
  return [
    ...TELECOM_SITES,
    ...PROJECT_SITES,
    ...TRAFFIC_SITES,
    ...SCHOOL_SITES,
    ...RESIDENTIAL_SITES,
  ];
}

export function findByCode(code: string): UssapSite | undefined {
  const n = code.replace(/[^0-9A-Z]/gi, "").toUpperCase();
  return allSites().find((s) => s.code.replace(/[^0-9A-Z]/gi, "") === n);
}

export const BRAND = {
  name: "USSAP",
  fullName: "Unified Smart Spatial Addressing Platform",
  tagline: "Precise digital addresses for Nigeria’s critical places",
};
